### ISSUE TITLE
--

### ISSUE THREAD

**Issue by LifeToyer** [TCLOpenSource/rt2851mr#1]

**Comment by bra-daydayup** [comment]
> 开发者，您好，好不容易找到您， 我的TCL 65X925在上周写入R51MT06-LF1V029的IMG后，表现为HDMI1和2输入有画面无声音，HDMI3始终输入一个1080p的全屏紫色信号（即使HDMI3没有插入任何输入源），此问题出现后，我继续尝试刷入R51MT06-LF1V114的IMG、甚至刷入最初的R51MT02-LF1R011.019533，故障依旧存在。现在电视处于完全不能用的状态。 由于是外销版本，国内售后无法解决，所有才找到您，希望您或者您的同事可以帮我们修复这个问题，目前为止已有6人出现这个问题了。 期待您的回复，祝您生活愉快。

刷入R51MT06-LF1V029的IMG前HDMI输入是正常有声音有画面的，当时的版本号是R51MT01-LFR999.019642

**Comment by jaywongs** [comment]
这个问题你解决了吗？
